# -*- coding: utf-8 -*-
"""Tarea 1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pGU7v3m0fRqbuShHymummOh0uOpT7_65
"""

print ('Hola mundo')